# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # Pull requests targeting this branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ~/.composer
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/composer.lock') }}
      - name: List files
        run: ls -ltra
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Check PHP is installed
        run: php -v
      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      - name: Install FE Dependencies
        run: npm ci
      - name: Build FE Dependencies
        run: npm run build
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-artifact
          path: ./routes
          retention-days: 1
      - name: List files2
        run: ls ~ -ltrah

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Staging
    steps:
      - name: Retrieve saved artifact
        uses: actions/download-artifact@v2
        with:
          name: output-artifact
          path: ./routes

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
    steps:
      - name: Retrieve saved artifact
        uses: actions/download-artifact@v2
        with:
          name: output-artifact
          path: ./routes
